### ISSUE TITLE
副本區域範圍領地權限和進入副本區域提示

### ISSUE THREAD

**Issue by Vincentex** [TonyFoster/mcark#36]
依據基本法 第4條 攻略野外王時可以合理合法發起戰鬥 但是在小穢物副本區域內因為領地沒有設置權限而無法戰鬥
即使有其他致人死地的方法 但是少了直接戰鬥就少去了大多數傷害人的手段 而在爭奪副本戰利品時 戰鬥應是可容許的
以下是12/31號 Neo_Demon 與 Omega_Devil 實測 無法在小穢物副本內傷害到彼此
![2020-12-31_11 29 12](https://user-images.githubusercontent.com/75464129/103393148-3ef12e80-4b5c-11eb-8a04-b23b51141cce.png)
另外這是京城的昏君副本 但因領地機制特殊 所以可以自由傷害到對方 便無這個問題
![2020-12-31_11 33 17](https://user-images.githubusercontent.com/75464129/103393296-e2dada00-4b5c-11eb-89a0-097c0ce5fa11.png)

至於 因為小穢物副本的佔據面積大 和 副本地形較複雜 所以可能要請OP自行決定此副本區域的何處能發起戰鬥或在議論堂討論
以及 不管最後範圍定在哪裡
希望昏君和小穢物副本在進入無責任戰鬥區域時可以像以前的副本在對話框或以其他形式明顯的顯示此處為無責任戰鬥區域
以免引起爭論或是不必要的麻煩

此issue如果被關閉 則視為上述機制和細節無須修改  並在日後不會提出同樣建議

**Comment by Vincentex** [comment]
此案件後續請見 https://github.com/TonyFoster/mcark/issues/37

**Comment by TonyFoster** [comment]
已設置無責戰鬥區域
