### ISSUE TITLE
無責任戰鬥區域訂定提案

### ISSUE THREAD

**Issue by Vincentex** [TonyFoster/mcark#37]
玩家爭奪副本首領戰利品時須要有合理的,正當的法律規範去保證欲爭奪戰利品的玩家
並且為了減少爭議 和 大多誤判 進入無責任戰鬥區域後 所有的戰鬥 和 物品拾取 等 視為挑起戰鬥的行為皆許可 不違法
且 進入無責任戰鬥區域時 需要有明顯的提示 比如對話框顯示 等...
目前只有副本需要這種區域

以下是建議的無責任戰鬥區範圍
1. 京城 - 清君側
此區域為方形 所以比較好判定
錦衣衛在大殿前的柱子 可以很清楚的知道 這裡有 有傷害性的怪物 且在一定範圍內可以遠離他們
因此建議的範圍即是 由4邊柱子組成的方形往內的所有範圍即是無責任戰鬥區域

柱子:
![2020-12-31_15 08 44](https://user-images.githubusercontent.com/75464129/103399052-37408280-4b7a-11eb-9f1d-661e5e8ef931.png)

2. 薩洛尼奧 - 最終處置設施

此副本的地形極為複雜
**"因此簡單來說 城堡內部的房間都是無責任戰鬥區域"**
且 因為領地系統是只能包方形區塊
可能在設置無責任區域時 要考慮一下 最佳覆蓋的範圍

以下是詳細位置
有兩個路口
從此拱門進入 慢慢深入的各個場景
![2020-12-31_14 32 25](https://user-images.githubusercontent.com/75464129/103398647-9dc4a100-4b78-11eb-8477-90cd07363727.png)
![2020-12-31_14 32 43](https://user-images.githubusercontent.com/75464129/103398651-a321eb80-4b78-11eb-8294-2145a6122abf.png)
![2020-12-31_14 32 49](https://user-images.githubusercontent.com/75464129/103398660-a7e69f80-4b78-11eb-8512-0cabe6def8af.png)
![2020-12-31_14 33 41](https://user-images.githubusercontent.com/75464129/103398664-afa64400-4b78-11eb-872c-b26068df69ec.png)
![2020-12-31_14 33 59](https://user-images.githubusercontent.com/75464129/103398672-b8971580-4b78-11eb-808e-95be06732621.png)
![2020-12-31_14 34 32](https://user-images.githubusercontent.com/75464129/103398679-c187e700-4b78-11eb-8fd6-68b26f7aefab.png)
![2020-12-31_14 35 13](https://user-images.githubusercontent.com/75464129/103398693-cea4d600-4b78-11eb-90db-29ac40421683.png)
![2020-12-31_14 36 54](https://user-images.githubusercontent.com/75464129/103398700-d4022080-4b78-11eb-88f6-91b1c944b1e7.png)

--------------------------------------------------------------------------------------------------------------------------

如果是從這側拱門進入
![2020-12-31_14 37 36](https://user-images.githubusercontent.com/75464129/103398807-35c28a80-4b79-11eb-8081-fb8250ae4b86.png)
![2020-12-31_14 39 33](https://user-images.githubusercontent.com/75464129/103398822-4410a680-4b79-11eb-82c8-ff0b9184fb4b.png)
![2020-12-31_14 39 14](https://user-images.githubusercontent.com/75464129/103398818-3f4bf280-4b79-11eb-9722-f29028e74b3c.png)
![2020-12-31_14 38 52](https://user-images.githubusercontent.com/75464129/103398813-3bb86b80-4b79-11eb-86e8-aa2365bff6e1.png)

以上 為我本人建議的無責任戰鬥區域規則 和 建議設置位置

如果此issue被關閉 則提案被否決 我則會重新提案或等待他人有更好的解答

**Comment by TonyFoster** [comment]
已設置無責戰鬥區域
