### ISSUE TITLE
領地折扣未使用，從685剩25

### ISSUE THREAD

**Issue by RChe77** [TonyFoster/mcark#42]
![未命名](https://user-images.githubusercontent.com/74287723/103449049-5d326800-4cdd-11eb-82f7-b232314edd9d.png)

詢問了兩三個玩家，都有同樣的問題，未使用領地折扣，但折扣餘額都剩下25

**Comment by TonyFoster** [comment]
被終界龍吃折扣

**Comment by RChe77** [comment]
終界龍還錢!! ヽ(#`Д´)ﾉ

**Comment by TonyFoster** [comment]
修正了
