### ISSUE TITLE
行政區應不可使用漏斗、投擲器、發射器輸入物品至另一行政區之任何可收納方塊

### ISSUE THREAD

**Issue by BeanDoZ** [TonyFoster/mcark#53]

**Comment by BeanDoZ** [comment]
請注意投擲器、發射器應清空或停止，否則使用紅石可噴出並在另一行政區使用漏斗接取

**Comment by BeanDoZ** [comment]
補充：界伏盒可被推落成掉落物，考慮直接禁止紅石使用

**Comment by TonyFoster** [comment]
行政區邊界外：
- 不能用活塞推拉方塊
- 不能啟動任何紅石
- 漏斗不能傳輸物品

**Comment by TonyFoster** [comment]
Entity damage related events should also been disabled.

**Comment by TonyFoster** [comment]
Try disable any modifications outside the border.

**Comment by TonyFoster** [comment]
done
