### ISSUE TITLE
設置1*1、1*N的領地大小，會偵測不到領地

### ISSUE THREAD

**Issue by RChe77** [TonyFoster/mcark#66]
在殖民地測試，設置1x1、1xN的領地大小，會錯誤顯示所在位置沒有領地，領地主也無法對該領地進行命名、修改權限、刪除等(偵測不到領地)，但該地實際是存在的，他人無法破壞及重複設置，2x2或以上的大小是正常的。
BTW 本問題和"薩洛尼奧多處領地異常"及OB1/11在DC議事堂提的問題應該是同樣的。🤔
![2021-01-17_18 03 32](https://user-images.githubusercontent.com/74287723/104838610-fe810700-58f6-11eb-8bf8-287e5ce437b1.png)
![2021-01-17_18 03 59](https://user-images.githubusercontent.com/74287723/104838612-02ad2480-58f7-11eb-8209-2d3d5f830d77.png)

**Comment by TonyFoster** [comment]
已修正
